import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import updateLocale from "dayjs/plugin/updateLocale";
import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";
import Image from "next/image";
import { LoadingPage } from "~/components/loading";

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

dayjs.extend(relativeTime);
dayjs.extend(updateLocale);
dayjs.updateLocale("es", {
  relativeTime: {
    m: "m",
    h: "h",
  },
});

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  console.log(user, "user");

  return (
    <div className="flex gap-4">
      <Image
        src={user.profileImageUrl}
        alt="profile image"
        className="h-12 w-12 rounded-full"
        width={48}
        height={48}
      />
      <input
        type="text"
        className="grow bg-transparent text-xl outline-none"
        placeholder="What's happening?"
      />
    </div>
  );
};

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div className="flex cursor-pointer flex-row gap-3 border-b border-b-zinc-700 px-4 py-3 transition-all duration-200 hover:bg-zinc-950">
      <Image
        className="h-12 w-12 rounded-full"
        src={author.profileImageUrl}
        alt={`${author.username}'s profile picture`}
        width={48}
        height={48}
      />
      <div className="flex flex-col">
        <div className="flex flex-row space-x-1">
          <div className="font-bold">{author?.name}</div>
          <div className="text-zinc-500">@{author?.username}</div>
          <span className="ml-2 text-zinc-500">·</span>
          <div className="text-zinc-500">{dayjs(post.createdAt).fromNow()}</div>
        </div>
        <div>{post.content}</div>
      </div>
    </div>
  );
};

const Feed = () => {
  const { data, isLoading: postLoading } = api.posts.getAll.useQuery();

  if (postLoading) return <LoadingPage />;

  if (!data) return <div>Something went wrong!</div>;

  return (
    <div className="flex flex-col text-white ">
      {data.map((fullPost) => (
        <PostView {...fullPost} key={fullPost.post.id} />
      ))}
    </div>
  );
};

const Home: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  api.posts.getAll.useQuery();

  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-zinc-700 md:max-w-[598px]">
          <div className="flex border-b border-zinc-700 p-4">
            {!isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {isSignedIn && <CreatePostWizard />}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
