import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { RouterOutputs, api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  console.log(user, "user");

  return (
    <div className="flex gap-4">
      <img
        src={user.profileImageUrl}
        alt="profile image"
        className="h-12 w-12 rounded-full"
      />
      <input
        type="text"
        className="grow bg-transparent text-xl outline-none"
        placeholder="What's happening?"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div className="flex cursor-pointer flex-row gap-3 border-b border-b-zinc-700 px-4 py-3 transition-all duration-200 hover:bg-zinc-950">
      <img
        className="h-12 w-12 rounded-full"
        src={author.profileImageUrl}
        alt={`${author?.name}'s profile picture`}
      />
      <div className="flex flex-col">
        <div className="flex flex-row space-x-1">
          <div className="font-bold">{author?.name}</div>
          <div className="text-zinc-500">@{author?.username}</div>
          <div className="ml-2 text-zinc-500">·</div>
        </div>
        <div>{post.content}</div>
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();
  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Not found</div>;

  console.log(data);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-zinc-700 md:max-w-[598px]">
          <div className="flex border-b border-zinc-700 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col text-white ">
            {data.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.author.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
